openapi: 3.0.1
info:
  title: langfuse
  version: ''
paths:
  /api/events:
    post:
      description: Add an event to the database
      operationId: event_create
      tags:
        - Event
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
  /api/spans:
    post:
      description: Add a span to the database
      operationId: span_create
      tags:
        - Span
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Span'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSpanRequest'
    patch:
      description: Update a span to the database
      operationId: span_update
      tags:
        - Span
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Span'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSpanRequest'
  /api/traces:
    post:
      description: Add a trace to the database
      operationId: trace_create
      tags:
        - Trace
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trace'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTraceRequest'
components:
  schemas:
    CreateEventRequest:
      title: CreateEventRequest
      type: object
      properties:
        traceId:
          type: string
        name:
          type: string
        startTime:
          type: string
          format: date-time
        attributes: {}
        parentObservationId:
          type: string
      required:
        - traceId
        - name
        - startTime
        - attributes
    Event:
      title: Event
      type: object
      properties:
        id:
          type: string
        traceId:
          type: string
        type:
          type: string
        name:
          type: string
        startTime:
          type: string
          format: date-time
        attributes: {}
        parentObservationId:
          type: string
      required:
        - id
        - traceId
        - type
        - name
        - startTime
        - attributes
    CreateSpanRequest:
      title: CreateSpanRequest
      type: object
      properties:
        traceId:
          type: string
        name:
          type: string
        startTime:
          type: string
          format: date-time
        attributes: {}
        parentObservationId:
          type: string
      required:
        - traceId
        - name
        - startTime
        - attributes
    UpdateSpanRequest:
      title: UpdateSpanRequest
      type: object
      properties:
        spanId:
          type: string
        endTime:
          type: string
          format: date-time
      required:
        - spanId
        - endTime
    Span:
      title: Span
      type: object
      properties:
        id:
          type: string
        traceId:
          type: string
        type:
          type: string
        name:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        attributes: {}
        parentObservationId:
          type: string
      required:
        - id
        - traceId
        - type
        - name
        - startTime
        - attributes
    CreateTraceRequest:
      title: CreateTraceRequest
      type: object
      properties:
        name:
          type: string
        attributes: {}
        status:
          type: string
        statusMessage:
          type: string
      required:
        - name
        - attributes
        - status
    Trace:
      title: Trace
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        name:
          type: string
        attributes: {}
        status:
          type: string
        statusMessage:
          type: string
      required:
        - id
        - timestamp
        - name
        - attributes
        - status
  securitySchemes: {}
servers:
  - url: https://www.yoursite.com
    description: production
  - url: https://www.staging.yoursite.com
    description: staging (This staging environment is helpful for testing!)
  - url: http://localhost:3001
    description: local (This local environment is helpful for testing locally!)
